# Generated by Django 5.1.3 on 2025-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teilnahmeantrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firmenname", models.CharField(max_length=200)),
                ("adresse", models.TextField()),
                ("ansprechpartner", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("wirtschaftliche_verknuepfungen", models.TextField(blank=True)),
                ("insolvenz", models.BooleanField(default=False)),
                ("straftat", models.BooleanField(default=False)),
                ("fehlende_abgaben", models.BooleanField(default=False)),
                ("umsatz_2023", models.DecimalField(decimal_places=2, max_digits=12)),
                ("umsatz_2022", models.DecimalField(decimal_places=2, max_digits=12)),
                ("umsatz_2021", models.DecimalField(decimal_places=2, max_digits=12)),
                ("berufshaftpflicht_vorhanden", models.BooleanField(default=False)),
                (
                    "berufshaftpflicht_nachweis",
                    models.FileField(blank=True, null=True, upload_to="nachweise/"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
