# Generated by Django 5.1.3 on 2025-05-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_teilnahmeantrag"),
    ]

    operations = [
        migrations.AddField(
            model_name="teilnahmeantrag",
            name="projektleitung",
            field=models.CharField(
                default="Unbekannt", help_text="Name der Projektleitung", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teilnahmeantrag",
            name="referenz_1",
            field=models.TextField(
                default="wird nachgereicht",
                help_text="Beschreibung eines Referenzprojekts",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teilnahmeantrag",
            name="referenz_2",
            field=models.TextField(
                blank=True, help_text="Optionales weiteres Referenzprojekt"
            ),
        ),
        migrations.AddField(
            model_name="teilnahmeantrag",
            name="referenz_upload",
            field=models.FileField(
                blank=True,
                help_text="Nur PDF zulässig",
                null=True,
                upload_to="referenzen/",
            ),
        ),
        migrations.AddField(
            model_name="teilnahmeantrag",
            name="team_groesse",
            field=models.IntegerField(
                default=0, help_text="Anzahl Mitarbeitende im Projektteam"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teilnahmeantrag",
            name="zustandigkeit_bauleitung",
            field=models.CharField(
                blank=True, help_text="Verantwortlich für Bauleitung", max_length=100
            ),
        ),
    ]
