# Generated by Django 4.2.21 on 2025-05-19 22:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_teilnahmeantrag_projektleitung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahmeantrag',
            name='is_brutto',
            field=models.BooleanField(default=True, help_text='Check if Umsatz is Brutto (incl. tax). Uncheck for Netto.'),
        ),
        migrations.AddField(
            model_name='teilnahmeantrag',
            name='steuer_satz',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Steuersatz in Prozent, z.B. 19.00', max_digits=4),
        ),
    ]
