# Generated by Django 4.2.21 on 2025-06-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_projekt_alter_teilnahmeantrag_is_brutto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahmeantrag',
            name='gesamt_score',
            field=models.IntegerField(blank=True, help_text='Summenpunktzahl (auto-berechnet)', null=True),
        ),
        migrations.AddField(
            model_name='teilnahmeantrag',
            name='score_anforderung1',
            field=models.IntegerField(blank=True, help_text='Punkte (0–10) für Kriterium 1', null=True),
        ),
        migrations.AddField(
            model_name='teilnahmeantrag',
            name='score_anforderung2',
            field=models.IntegerField(blank=True, help_text='Punkte (0–10) für Kriterium 2', null=True),
        ),
    ]
