# Generated by Django 4.2.21 on 2025-06-01 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_teilnahmeantrag_gesamt_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahmeantrag',
            name='user',
            field=models.ForeignKey(default=2, help_text='Der Bieter, der diesen Antrag eingereicht hat', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
