# Generated by Django 4.2.21 on 2025-06-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_teilnahmeantrag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='deadline',
            field=models.DateField(),
        ),
    ]
