# Generated by Django 4.2.21 on 2025-06-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_teilnahmeantrag_projekt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='deadline',
            field=models.DateField(help_text='Einsendeschluss für Anträge'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='name',
            field=models.CharField(help_text='Projektname', max_length=200),
        ),
    ]
