# Generated by Django 4.2.21 on 2025-06-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_frage_options_frage_field_type_frage_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnahmeantrag',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Kriterium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Beschreiben Sie das Kriterium', max_length=500)),
                ('max_punkte', models.PositiveSmallIntegerField(default=10, help_text='Maximale Punktzahl (z. B. 10)')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriterien', to='portal.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkte', models.PositiveSmallIntegerField()),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewertungen', to='portal.teilnahmeantrag')),
                ('kriterium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewertungen', to='portal.kriterium')),
            ],
            options={
                'unique_together': {('antrag', 'kriterium')},
            },
        ),
    ]
