# Generated by Django 4.2.21 on 2025-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_teilnahmeantrag_adresse_kriterium_bewertung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bewertung',
            options={'verbose_name': 'Bewertung', 'verbose_name_plural': 'Bewertungen'},
        ),
        migrations.AlterModelOptions(
            name='frage',
            options={'ordering': ['order'], 'verbose_name': 'Frage', 'verbose_name_plural': 'Fragen'},
        ),
        migrations.AlterModelOptions(
            name='kriterium',
            options={'verbose_name': 'Kriterium', 'verbose_name_plural': 'Kriterien'},
        ),
        migrations.AlterModelOptions(
            name='projekt',
            options={'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekte'},
        ),
        migrations.AlterModelOptions(
            name='teilnahmeantrag',
            options={'verbose_name': 'Teilnahmeantrag', 'verbose_name_plural': 'Teilnahmeanträge'},
        ),
        migrations.AlterField(
            model_name='teilnahmeantrag',
            name='team_groesse',
            field=models.IntegerField(help_text='Anzahl Mitarbeitende im Projektteam', verbose_name='Team-Größe'),
        ),
    ]
