# Generated by Django 4.2.21 on 2025-06-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_bewertung_options_alter_frage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewertung',
            name='erstellt_am',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
