# Generated by Django 4.2.21 on 2025-06-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_bewertung_erstellt_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahmeantrag',
            name='bewertungen_data',
            field=models.JSONField(blank=True, default=dict, help_text='Speichert die Punkte/Kommentare aus Bewertungen'),
        ),
        migrations.AlterField(
            model_name='teilnahmeantrag',
            name='antworten',
            field=models.JSONField(blank=True, default=dict, help_text='...'),
        ),
    ]
