# Generated by Django 4.2.21 on 2025-06-05 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_projekt_deadline_alter_projekt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='portal.projekt')),
            ],
        ),
    ]
