# Generated by Django 4.2.21 on 2025-06-22 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_teilnahmeantrag_bewertungen_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Land')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Firmenname')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
